export interface AvailableSubject {
  id: string;
  name: string;
  prof: string;
  career: string;
  term: string;
  time: string;
  room: string;
  day: string;
}

export const availableSubjects: AvailableSubject[] = [
  { id: 'abordajes-psp', name: 'ABORDAJES PSP en ADULTOS MAYORES', prof: 'DONATO, ANDREA', career: 'C.P. 3º', term: '1º y 2º', time: '17:40 a 20:20', room: '101', day: 'Miércoles' },
  { id: 'analisis-discurso', name: 'ANÁLISIS DEL DISCURSO', prof: 'BETTENDORFF, PAULINA', career: 'LTR 5', term: '1º', time: '18:20 a 22:20', room: 'AUSENTE', day: 'Miércoles' },
  { id: 'antropologia', name: 'ANTROPOLOGÍA', prof: 'CERRA, CAMILA', career: 'H2', term: '1º y 2º', time: '18:20 a 21:00', room: '305', day: 'Miércoles' },
  { id: 'biologia', name: 'BIOLOGÍA', prof: 'VARGAS, CLAUDIA', career: 'PSI 2', term: '1º', time: '18:20 a 20:20', room: '3', day: 'Miércoles' },
  { id: 'didactica-general-1', name: 'DIDÁCTICA GENERAL', prof: 'LAVIN, EDUARDO', career: 'CFG', term: 'AN.', time: '18:20 a 20:20', room: '302', day: 'Miércoles' },
  { id: 'didactica-general-2', name: 'DIDÁCTICA GENERAL', prof: 'GARCÍA, DANIELA', career: 'C.P. 1º', term: 'AN.', time: '17:40 a 19:40', room: '404', day: 'Miércoles' },
  { id: 'didactica-general-3', name: 'DIDÁCTICA GENERAL', prof: 'DEL CASTILLO, VERÓNICA', career: 'C.P. 1º', term: 'AN.', time: '18:20 a 20:20', room: 'Salón', day: 'Miércoles' },
  { id: 'epistemologia', name: 'EPISTEMOLOGÍA e HISTORIA DE LA HISTORIOGRAFÍA', prof: 'MARTÍNEZ, ILANA', career: 'H5', term: 'AN.', time: '20:20 a 23:00', room: '1', day: 'Miércoles' },
  { id: 'espacio-practica-2', name: 'ESPACIO DE LA PRÁCTICA II', prof: 'MENCHÓN, ÁNGELA', career: 'FILO 4', term: 'AN.', time: '20:20 a 23:00', room: '1', day: 'Miércoles' },
  { id: 'estrategias-conflictos', name: 'ESTRATEGIAS para la RESOLUCIÓN de CONFLICTOS', prof: 'ZITO LEMA, VANESA', career: 'PSI 5', term: '1º y 2º', time: '20:20 a 22:20', room: '401', day: 'Miércoles' },
  { id: 'etica', name: 'ÉTICA', prof: 'SANTAYA, DARÍO', career: 'FILO 3', term: 'AN.', time: '20:20 a 23:00', room: '304', day: 'Miércoles' },
  { id: 'filosofia-1', name: 'FILOSOFÍA', prof: 'GERSZENZON, LUCÍA', career: 'CFG', term: 'AN.', time: '17:40 a 20:20', room: '205', day: 'Miércoles' },
  { id: 'filosofia-ciencias', name: 'FILOSOFÍA DE LAS CIENCIAS', prof: 'CÁRDENES RAMIRO', career: 'FILO 3', term: 'AN.', time: '17:40 a 20:20', room: '200', day: 'Miércoles' },
  { id: 'historia-cultura', name: 'HISTORIA DE LA CULTURA', prof: 'DEVES, MAGALÍ ANDREA', career: 'H4', term: '1º', time: '19:00 a 21:00', room: 'Biblioteca', day: 'Miércoles' },
  { id: 'historia-moderna', name: 'HISTORIA MODERNA', prof: 'BUBELLO, JUAN', career: 'H3', term: 'AN.', time: '17:40 a 21:00', room: '2', day: 'Miércoles' },
  { id: 'historia-reciente', name: 'HISTORIA RECIENTE', prof: 'ARBELO, HERNANDO', career: 'H4', term: 'AN.', time: '21:00 a 23:00', room: '305', day: 'Miércoles' },
  { id: 'lengua-cultura-latinas-2', name: 'LENGUA Y CULTURA LATINAS II', prof: 'DIOLAITI, ENZO', career: 'LTR 3', term: 'AN.', time: '19:00 a 23:00', room: '400', day: 'Miércoles' },
  { id: 'literatura-latinoamericana', name: 'LITERATURA LATINOAMERICANA', prof: 'COBAS CARRAL, ANDREA', career: 'LTR 4', term: '1º', time: '18:20 a 22:20', room: '402', day: 'Miércoles' },
  { id: 'neurociencias-educacion', name: 'NEUROCIENCIAS y EDUCACIÓN', prof: 'CAO, STELLA', career: 'PSI 5', term: '1º y 2º', time: '20:20 a 23:00', room: '200', day: 'Miércoles' },
  { id: 'orientacion-educacional', name: 'ORIENTACIÓN EDUCACIONAL, VOCACIONAL Y PROFESIONAL', prof: 'CAJOTO, YANINA', career: 'C.P. 4º', term: 'AN.', time: '17:40 a 20:20', room: '201', day: 'Miércoles' },
  { id: 'pedagogia-1', name: 'PEDAGOGÍA', prof: 'GARCÍA, DANIELA', career: 'C.P. 1º', term: 'AN.', time: '19:40 a 23:00', room: '404', day: 'Miércoles' },
  { id: 'pedagogia-2', name: 'PEDAGOGÍA', prof: 'RAMAS, FERNANDA', career: 'CFG', term: 'AN.', time: '17:40 a 19:40', room: '301', day: 'Miércoles' },
  { id: 'pedagogia-3', name: 'PEDAGOGÍA', prof: 'DEL CASTILLO, VERÓNICA', career: 'C.P. 1º', term: 'AN.', time: '17:40 a 21:00', room: 'Salón', day: 'Miércoles' },
  { id: 'prehistoria-general', name: 'PREHISTORIA GENERAL Y CULTURAS AMERICANAS', prof: 'MANZI, LILIANA', career: 'H1', term: 'AN.', time: '19:00 a 22:20', room: '306', day: 'Miércoles' },
  { id: 'psicologia-adolescencia', name: 'PSICOLOGÍA de la ADOLESCENCIA y la ADULTEZ', prof: 'ALVAREZ, BLANCA', career: 'C.P. 2º', term: '1º', time: '18:20 a 22:20', room: '206', day: 'Miércoles' },
  { id: 'psicologia-educacion', name: 'PSICOLOGÍA DE LA EDUCACIÓN', prof: 'RATTI, FEDERICO', career: 'PSI 3', term: 'AN.', time: '17:40 a 20:20', room: '304', day: 'Miércoles' },
  { id: 'psicologia-ninez-1', name: 'PSICOLOGÍA DE LA NIÑEZ', prof: 'ACUÑA, MARÍA INÉS', career: 'C.P. 2º', term: '1º', time: '17:40 a 21:40', room: '307', day: 'Miércoles' },
  { id: 'psicologia-ninez-2', name: 'PSICOLOGÍA DE LA NIÑEZ', prof: 'PENNELLA, MARÍA', career: 'PSI 2', term: 'AN.', time: '20:20 a 23:00', room: '403', day: 'Miércoles' },
  { id: 'psicologia-educacional', name: 'PSICOLOGÍA EDUCACIONAL', prof: 'VALENZUELA, CRISTIAN', career: 'CFG', term: '1º y 2º', time: '20:20 a 23:00', room: '302', day: 'Miércoles' },
  { id: 'psicopedagogia-laboral', name: 'PSICOPEDAGOGÍA LABORAL', prof: 'AMATO, MONICA', career: 'C.P. 3º', term: '1º y 2º', time: '17:40 a 20:20', room: '303', day: 'Miércoles' },
  { id: 'sistema-politica-educativa', name: 'SISTEMA Y POLÍTICA EDUCATIVA', prof: 'GALARZA, DANIEL', career: 'CFG', term: '1º y 2º', time: '20:20 a 23:00', room: '101', day: 'Miércoles' },
  { id: 'subjetividad-grupos', name: 'SUBJETIVIDAD, GRUPOS, INSTITUCIONES Y SOCIEDAD', prof: 'ZITO LEMA, VANESA', career: 'PSI 1', term: 'AN.', time: '18:20 a 20:20', room: '401', day: 'Miércoles' },
  { id: 'taller-analisis-imagen', name: 'TALLER DE ANÁLISIS DE LA IMAGEN', prof: 'GORFINKIEL, Lara', career: 'LTR 1', term: '1º y 2º', time: '19:40 a 21:40', room: '203', day: 'Miércoles' },
  { id: 'taller-practicas-2-1', name: 'Taller de Prácticas Profesionalizantes II: Residencia', prof: 'TORRE, GISELA', career: 'C.P. 4º', term: '1º y 2º', time: '20:20 a 23:00', room: '204', day: 'Miércoles' },
  { id: 'taller-practicas-2-2', name: 'Taller de Prácticas Profesionalizantes II: Residencia', prof: 'TORRE, GISELA', career: 'C.P. 4º', term: '1º y 2º', time: '17:40 a 20:20', room: '204', day: 'Miércoles' },
  { id: 'taller-analisis-cine', name: 'TALLER: ANÁLISIS DE CINE', prof: '(Sin docente)', career: 'LTR 1', term: '1º y 2º', time: '19:40 a 21:40', room: '-', day: 'Miércoles' },
  { id: 'taller-lectura-1', name: 'TALLER: LECTURA, ESCRITURA Y ORALIDAD I', prof: 'CARRANZA, GONZALO', career: 'CFG', term: 'AN.', time: '16:00 a 18:00', room: '4', day: 'Miércoles' },
  { id: 'taller-lectura-2', name: 'TALLER: LECTURA, ESCRITURA Y ORALIDAD II', prof: 'CARRANZA, GONZALO', career: 'CFG/PSI/H', term: '1º y 2º', time: '21:00 a 23:00', room: '2', day: 'Miércoles' },
  { id: 'tec-proyectivas', name: 'TEC. PROYECTIVAS DE DIAG. APLICADAS...', prof: 'PENNELLA, MARÍA', career: 'PSI 4', term: '1º', time: '17:40 a 20:20', room: '403', day: 'Miércoles' },
  { id: 'teoria-tecnicas-proyectivas', name: 'TEORÍA Y TÉCNICAS PROYECTIVAS DE EVALUACIÓN', prof: 'GRISOLÍA, ERICA', career: 'C.P. 3º', term: 'AN.', time: '20:20 a 23:00', room: '3', day: 'Miércoles' },
  { id: 'trabajo-campo', name: 'TRABAJO DE CAMPO', prof: 'MARTIN/BENITEZ, SAULO', career: 'H2', term: 'AN.', time: '21:00 a 23:00', room: '303', day: 'Miércoles' },
  { id: 'antropologia-martes', name: 'ANTROPOLOGÍA', prof: 'RUSSO, MARLENE', career: '', term: '1º y 2º', time: '17:40 a 20:20', room: '306', day: 'Martes' },
  { id: 'asia-africa', name: 'ASIA Y AFRICA EN EL SISTEMA MUNDO', prof: 'CIMOLI, RICARDO PEDRO', career: 'H5', term: 'AN.', time: '17:40 a 20:20', room: '400', day: 'Martes' },
  { id: 'bases-neurofisiologicas', name: 'BASES NEUROFISIOLÓGICAS DEL APRENDIZAJE', prof: 'VARGAS, CLAUDIA', career: 'C.P 1º A', term: 'AN.', time: '20:20 a 23:00', room: 'Salón', day: 'Martes' },
  { id: 'clinica-psp-1', name: 'CLÍNICA PSP EN ADOLESCENTES Y ADULTOS', prof: 'ITURRIOZ, MICAELA', career: 'C.P 4º A', term: 'AN.', time: '17:40 a 21:00', room: '206', day: 'Martes' },
  { id: 'clinica-psp-2', name: 'CLÍNICA PSP EN ADOLESCENTES Y ADULTOS', prof: 'CANTARELLI, SUSANA', career: 'C.P 4º B', term: 'AN.', time: '17:40 a 21:00', room: '403', day: 'Martes' },
  { id: 'construccion-practica', name: 'CONSTRUCCIÓN DE LA PRÁCTICA DOCENTE I', prof: 'BENITEZ, EZEQUIEL', career: 'H3', term: 'AN.', time: '18:20 a 19:00', room: '203', day: 'Martes' },
  { id: 'didactica-historia', name: 'DIDÁCTICA DE LA HISTORIA PARA LOS NIVELES SEC. Y SUP. II', prof: 'ROLS, DIEGO', career: 'H4', term: '1º y 2º', time: '19:00 a 21:00', room: '4', day: 'Martes' },
  { id: 'didactica-lengua', name: 'DIDÁCTICA DE LA LENGUA Y LA LITERATURA II', prof: 'COLUSSI, ROMINA', career: 'LTR 4', term: '1º', time: '17:40 a 20:20', room: '302', day: 'Martes' },
  { id: 'didactica-nivel-medio', name: 'DIDÁCTICA EN EL NIVEL MEDIO Y SUPERIOR', prof: 'DE OLIVERA PEROTTO', career: 'PSI 3', term: 'AN.', time: '17:40 a 20:20', room: '305', day: 'Martes' },
  { id: 'didactica-general-martes-1', name: 'DIDÁCTICA GENERAL', prof: 'GACIOPPO, FLAVIA', career: 'CFG H2', term: '1º y 2º', time: '17:40 a 20:20', room: '204', day: 'Martes' },
  { id: 'didactica-general-martes-2', name: 'DIDÁCTICA GENERAL', prof: 'PERUGINI, YOLANDA', career: 'CFG', term: 'AN.', time: '17:40 a 19:40', room: '301', day: 'Martes' },
  { id: 'espacio-practica-1', name: 'ESPACIO DE LA PRÁCTICA I: SUJETOS Y CONTX. DE LA PRÁCTICA', prof: 'BERON, SERGIO', career: 'FILO 2', term: 'AN.', time: '20:20 a 23:00', room: '204', day: 'Martes' },
  { id: 'estadistica', name: 'ESTADÍSTICA', prof: 'TAJANI, LEILA', career: 'C.P 1º B', term: '1º y 2º', time: '19:00 a 23:00', room: '402', day: 'Martes' },
  { id: 'filosofia-martes', name: 'FILOSOFÍA', prof: 'DIVENOSA, MARISA', career: 'CFG', term: 'AN.', time: '20:20 a 23:00', room: 'AUSENTE', day: 'Martes' },
  { id: 'filosofia-politica', name: 'FILOSOFÍA POLÍTICA', prof: 'CARDENES, R.', career: 'FILO 5', term: '1º', time: '17:40 a 20:20', room: '200', day: 'Martes' },
  { id: 'frances-1', name: 'FRANCÉS 1', prof: 'GONZALEZ, SILVINA', career: 'Exten.', term: 'AN.', time: '18:20 a 20:20', room: 'BIBLIOTECA', day: 'Martes' },
  { id: 'historia-america-1', name: 'HISTORIA DE AMERICA I (Colonial)', prof: 'GARCIA, LORENA', career: 'H3', term: 'AN.', time: '19:00 a 22:20', room: '301', day: 'Martes' },
  { id: 'historia-america-3', name: 'HISTORIA DE AMERICA III (Siglo XX)', prof: 'HORTON, CARLA', career: 'H5', term: 'AN.', time: '20:20 a 23:00', room: '304', day: 'Martes' },
  { id: 'historia-filosofia-antigua', name: 'HISTORIA DE LA FILOSOFÍA ANTIGUA', prof: 'DIVENOSA, MARISA', career: 'FILO 1', term: 'AN.', time: '17:40 a 20:20', room: 'AUSENTE', day: 'Martes' },
  { id: 'intro-ciencias-lenguaje', name: 'INTRODUCCIÓN a las CIENCIAS del LENGUAJE', prof: 'BANNON, MARA', career: 'LTR 1', term: '1º', time: '17:40 a 20:20', room: '3', day: 'Martes' },
  { id: 'lengua-cultura-latinas-1', name: 'LENGUA y CULTURA LATINAS I', prof: 'DIOLAITI, ENZO', career: 'LTR 2', term: 'AN.', time: '19:00 a 23:00', room: '203', day: 'Martes' },
  { id: 'lenguajes-expresivos', name: 'LENGUAJES EXPRESIVOS APLICADOS A LA PSP', prof: 'BROQUA, GRACIELA', career: 'C.P 2º A', term: '1º y 2º', time: '20:20 a 23:00', room: '201', day: 'Martes' },
  { id: 'literatura-lengua-extranjera', name: 'LITERATURA EN LENGUA EXTRANJERA II', prof: 'FRANCHI, FULVIO', career: 'LTR 5', term: '1º y 2º', time: '18:20 a 22:20', room: 'Normal 1 Aula 13 C', day: 'Martes' },
  { id: 'logica-argumentacion', name: 'LÓGICA Y TEORÍA DE LA ARGUMENTACIÓN', prof: 'KAKAZU, GABRIEL', career: 'FILO 1', term: 'AN.', time: '20:20 a 23:00', room: '306', day: 'Martes' },
  { id: 'neuropsicopatologia', name: 'NEUROPSICOPATOLOGÍA', prof: 'DETLEFSEN, Mría Verónica', career: 'C.P 2º B', term: 'AN.', time: '17:40 a 20:20', room: '201', day: 'Martes' },
  { id: 'nuevos-escenarios', name: 'NUEVOS ESCENARIOS: CULTURA, TECNOLOGÍA Y SUBJETIVIDAD', prof: 'GONZALEZ MARTIN, M.', career: 'CFG', term: '1º', time: '20:20 a 23:00', room: '2', day: 'Martes' },
  { id: 'problemas-filosofia', name: 'PROBLEMAS de la FILOSOFÍA CONTEMPORÁNEA', prof: 'ARROYO, G.', career: 'FILO 4', term: 'AN.', time: '20:20 a 23:00', room: '200', day: 'Martes' },
  { id: 'promocion-prevencion', name: 'PROMOCIÓN y PREVENCIÓN en PSP', prof: 'MONTI, CECILIA', career: 'C.P 4º A/B', term: 'AN.', time: '21:00 a 23:00', room: '404', day: 'Martes' },
  { id: 'psicologia-educacional-martes', name: 'PSICOLOGÍA EDUCACIONAL', prof: 'CRISTELLI, CYNTHIA', career: 'CFG', term: '1º', time: '20:20 a 23:00', room: '205', day: 'Martes' },
  { id: 'psicologia-genetica', name: 'PSICOLOGÍA GENÉTICA', prof: 'SCHIAVELLO, M. GABRIELA', career: 'C.P 2º A', term: '1º y 2º', time: '18:20 a 22:20', room: '101', day: 'Martes' },
  { id: 'psicopatologia-1', name: 'PSICOPATOLOGÍA', prof: 'RONCHETTI, PABLO', career: 'PSI 4', term: 'AN.', time: '18:20 a 21:00', room: '401', day: 'Martes' },
  { id: 'psicopatologia-2', name: 'PSICOPATOLOGÍA', prof: 'AIME, CLAUDIO', career: 'C.P 3º A/B', term: 'AN.', time: '17:40 a 20:20', room: 'Salón', day: 'Martes' },
  { id: 'residencia', name: 'RESIDENCIA', prof: 'COLUSSI, ROMINA', career: 'LTR 5', term: '1º y 2º', time: '20:20 a 23:00', room: '303', day: 'Martes' },
  { id: 'seminario-filosofia-antigua', name: 'Seminario de Filosofía Antigua y Medieval', prof: 'TABAKIAN, DIEGO', career: 'FILO 3', term: 'AN.', time: '18:20 a 20:20', room: '1', day: 'Martes' },
  { id: 'seminario-filosofia-moderna', name: 'Seminario de Filosofía Moderna y Contemporánea', prof: 'MARTIN, JORGE', career: 'FILO 5', term: 'AN.', time: '21:00 a 23:00', room: 'EP', day: 'Martes' },
  { id: 'sociologia-1', name: 'SOCIOLOGÍA', prof: 'FRISCH, PABLO', career: 'C.P 1º A', term: '1º y 2º', time: '17:40 a 20:20', room: '404', day: 'Martes' },
  { id: 'sociologia-2', name: 'SOCIOLOGÍA', prof: 'SALTI, PATRICIA', career: 'C.P 1º B', term: '1º y 2º', time: '17:40 a 20:20', room: '307', day: 'Martes' },
  { id: 'taller-nuevas-tecnologias', name: 'Taller Acerca de las Problemáticas de las Nvas Tecnol...', prof: 'CONDE, MARIANA', career: 'PSI 5', term: '1º y 2º', time: '17:40 a 20:20', room: '303', day: 'Martes' },
  { id: 'taller-material-didactico', name: 'Taller de Análisis y Producción de Material Didáctico', prof: 'THISTED, MARCOS', career: 'FILO 4', term: '1º', time: '17:40 a 20:20', room: '304', day: 'Martes' },
  { id: 'taller-evaluacion', name: 'TALLER DE EVALUACIÓN', prof: 'CAO, STELLA', career: 'PSI 4', term: '1º y 2º', time: '21:00 a 23:00', room: '400', day: 'Martes' },
  { id: 'taller-literatura-gramatica', name: 'TALLER DE LITERATURA Y GRAMÁTICA', prof: 'GONZALEZ, SILVINA', career: 'Exten.', term: 'AN.', time: '20:20 a 22:20', room: 'BIBLIOTECA', day: 'Martes' },
  { id: 'taller-tecnicas-cuantitativas', name: 'Taller de Técnicas Cuantitativas de Inv. Aplicadas...', prof: 'RALON, GONZALO', career: 'PSI 3', term: '1º', time: '20:20 a 23:00', room: '1', day: 'Martes' },
  { id: 'taller-lectura-martes-1', name: 'TALLER: LECTURA, ESCRITURA Y ORALIDAD I', prof: 'LARA, MARCELO', career: 'CFG', term: 'AN.', time: '21:00 a 23:00', room: '401', day: 'Martes' },
  { id: 'taller-lectura-martes-2', name: 'TALLER: LECTURA, ESCRITURA Y ORALIDAD I', prof: 'WEBSTER, IAN', career: 'CFG', term: 'AN.', time: '18:20 a 20:20', room: 'Normal 1 Aula 13 B', day: 'Martes' },
  { id: 'teoria-social-latinoamericana', name: 'TEORÍA SOCIAL LATINOAMERICANA', prof: 'CHIARADIA, ESTEBAN', career: 'H4', term: '1º', time: '21:00 a 23:00', room: '4', day: 'Martes' },
  { id: 'trabajo-profesionalizacion', name: 'TRABAJO Y PROFESIONALIZACIÓN DOCENTE', prof: 'MARTINEZ GOMEZ, ERIKA', career: 'CFG', term: '1º y 2º', time: '20:20 a 23:00', room: '302', day: 'Martes' },
  { id: 'observacion-institucional', name: 'TALLER DE OBSERVACIÓN INSTITUCIONAL', prof: 'COLUSSI, ROMINA', career: 'LTR 1', term: '1º', time: '10:40 a 13:20', room: '1', day: 'Martes' },
  { id: 'ciencias-lenguaje', name: 'INTRODUCCIÓN a las CIENCIAS del LENGUAJE', prof: 'BANNON, MARA LIS', career: 'LTR 1', term: '1º', time: '17:40 a 20:20', room: '3', day: 'Martes' },
  { id: 'ciencias-lenguaje-viernes', name: 'INTRODUCCIÓN a las CIENCIAS del LENGUAJE', prof: 'BANNON, MARA LIS', career: 'LTR 1', term: '1º', time: '19:00 a 20:20', room: '3', day: 'Viernes' },
  { id: 'trabajo-docente', name: 'TRABAJO Y PROFESIONALIZACIÓN DOCENTE', prof: 'MARTINEZ GOMEZ, ERIKA', career: 'CFG', term: '1º y 2º', time: '20:20 a 23:00', room: '302', day: 'Martes' },
  { id: 'pedagogia', name: 'PEDAGOGÍA', prof: 'AGUILAR, SANDRA M.', career: 'CFG', term: 'AN.', time: '17:40 a 19:40', room: '301', day: 'Miércoles' },
  { id: 'taller-investigacion', name: 'TALLER DE INVESTIGACIÓN EN LENGUA Y LITERATURA', prof: 'DI MIRO, MELINA', career: 'LTR 4', term: '1º', time: '20:20 a 23:00', room: '2', day: 'Jueves' },
  { id: 'estudios-literarios', name: 'INTRODUCCIÓN A LOS ESTUDIOS LITERARIOS', prof: 'VÁZQUEZ, ROMINA L.', career: 'LTR 1', term: '1º', time: '09:20 a 11:20', room: '4', day: 'Viernes' },
  { id: 'psicoanalisis', name: 'PSICOANÁLISIS', prof: 'AIME, CLAUDIO', career: 'C.P. 2º B', term: 'AN.', time: '20:20 a 23:00', room: '307', day: 'Martes' }
];
